services:
  storages_lib:
    build:
      dockerfile: Dockerfile
      context: .docker/php
    container_name: storages_lib
    restart: "no"
    working_dir: /app
    volumes:
      - ./:/app

volumes:
  db:
networks:
  default:
    external: true
    name: shared-network
